clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  build:
    image: alpine
    commands:
      - sh test.sh
      - echo "eze" > ee.txt
  list:
    image: busybox
    commands:
      - cat ee.txt
      
